---
spring:
  profiles: local
  cloud:
    stream:
      kafka:
        binder:
          brokers: education-kafka:9092  # ${vcap.services.kakfa.host_port} and inject value from env variable
          zkNodes: education-kafka-zookeeper:2181
      bindings:
        class-topic:
          destination: bpm.topic
          contentType: application/json


server:
  port: 8098
  servletPath: /

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health
    metadataMap:
        deployment: local
        profile: local

---

spring:
  profiles: dev,stg,prod

server:
  port: 8080
  servletPath: /

eureka:
  client:
    enabled: false
